<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class bg_prduto extends Model
{
    use HasFactory;
    protected $fillable = [
        'PR_COD'
        , 'PR_NOM'
        , 'PR_NOM_REDUZ'
        , 'PR_PESOBR'
        , 'PR_PESOLQ'
        , 'PR_FLG_RECOL_PIS_COFINS'
        , 'PR_FLG_IMP_ETQ'
        , 'PR_FLG_ATIVO'
        , 'PR_ORIGEM'
        , 'PR_VAL_PRECO_CUSTO'
        , 'PR_VAL_ULT_PRCOM'
        , 'PR_DAT_ULTATU'
        , 'PR_DAT_CADSTR'
        , 'PR_PER_ISS'
        , 'DEPR_COD'
        , 'CAPR_COD'
        , 'PR_DAT_DESAT'
        , 'PR_INFORM_ADIC_PRDUTO'
        , 'UM_SIG_VENDA'
        , 'PR_FLG_VENDA'
        , 'PR_PER_MAX_DESC'
        , 'PR_FLG_INDCADOR_PESO'
        , 'UM_SIG_INTERN'
        , 'PR_FATOR_CONV'
        , 'PR_COD_PAI'
        , 'PR_PER_MARGEM_CUSTO_REAL'
        , 'PR_PER_MARGEM_PRECO_MINIMO'
        , 'PR_PER_MARGEM_PRECO_VENDA'
        , 'PR_PER_COMISS'
        , 'PR_VAL_ULT_PRCOM_DIF_ICMS'
        , 'GRPR_COD'
        , 'CLFI_COD'
        , 'PR_COD_SISTEM_ANT'
        , 'PR_QTD_EMBAL'
        , 'PR_PER_IPI'
        , 'CPC_COD_ENT'
        , 'CPC_COD_SAI'
        , 'CPCN_COD_ENT'
        , 'CPCN_COD_SAI'
        , 'PR_COD_BALANCA'
        , 'PR_PER_COMISS_QTD'
        , 'PR_INFORM_ADIC_NFE'
        , 'PR_LOCALIZ_ESTOQ'
        , 'MD_COD_VENDA'
        , 'PR_COD_COPIADO'
        , 'EM_COD_GRAVACAO'
        , 'FI_COD_GRAVACAO'
        , 'PR_FLG_INTG_ECOMMERCE'
        , 'EM_COD_GRAT'
        , 'GRAT_NUM_SEQ'
        , 'PR_FLG_ATT_INFO_ECOM'
        , 'TACE_COD_CEST'
        , 'PR_ALTURA'
        , 'PR_LARGURA'
        , 'PR_COMPRIMENTO'
        , 'PR_MARG_CALC_PRC_VEN_AUTO'
        , 'MCPR_COD'
        , 'PR_FLG_INF_QTD_SEP_CONF'
        , 'PR_INFO_ADIC_SFA'
        , 'PR_FLG_OBR_LEIT_EXPED'
        , 'PR_FLG_IMPORT_DIRETO'
        , 'PR_COD_AUX'
        , 'PR_FLG_CTRL_LOTE_VALID'
        , 'EM_COD_FAT'
        , 'FI_COD_FAT'
        , 'DAT_ATUALIZACAO'
        , 'USU_ATUALIZACAO'
        , 'PR_FLG_CTRL_NUM_SERIE'
        , 'PR_FLG_COMODATO'
        , 'PR_NOM_PDV'
        , 'PR_PER_COMISS_SN'
        , 'PR_PER_COMISS_CF'
        , 'PR_FLG_BLOQ_PED_SEM_ESTOQ'
        , 'PR_FLG_BASE_TINTA'
        , 'PR_TIPO_LATA_TINTA'
        , 'PR_FLG_OBG_TINTA'
        , 'PR_TIPO_COR'
        , 'EM_COD_GRAT_IPEV'
        , 'GRAT_NUM_SEQ_IPEV'
        , 'PR_TIPO_LADO'
        , 'EM_COD_VO_WMS'
        , 'FI_COD_VO_WMS'
        , 'VO_COD'
        , 'PR_QTD_VO_WMS'
        , 'PR_FLG_CONJUNTO_PRDUTO'
        , 'PR_FLG_SERVICO'
        , 'PR_FLG_CATALOGO_VENDA'
        , 'PR_FLG_BLOQ_ORC_SEM_ESTOQ'
        , 'PR_VAL_PLT_LARGURA'
        , 'PR_VAL_PLT_ALTURA'
        , 'PR_VAL_PLT_COMPRIMENTO'
        , 'PR_VAL_PLT_CUBAGEM'
        , 'PR_QTD_PLT_CAIXA'
        , 'PR_QTD_PLT_CAMADA'
        , 'PR_QTD_PLT_EMPILHAMENTO'
        , 'PR_VAL_PLT_PESO_BRUTO'
        , 'PR_CUBAGEM'
        , 'PR_COD_GRADE'
        , 'PR_OBS_FORNEC'
        , 'PR_COD_OEM'
        , 'PR_FLG_TIP_COD_LOTE'
        , 'PR_FLG_CONF_INDIVIDUAL'
        , 'PR_FLG_CONF_ETIQUETA'
        , 'PR_FLG_VENDA_MULT_EMBALAGEM'
        , 'CANP_COD'
        , 'PR_PER_GPL_DER_PETR'
        , 'PR_PER_GAS_NATUR_NAC'
        , 'PR_PER_GAS_NATUR_IMP'
        , 'PR_VAL_PARTIDA'
        , 'PR_FLG_IMPR_ETIQ_AUTO_CONF'
        , 'PR_FLG_SEPAR_INDIVIDUAL'
        , 'PR_FLG_CTRL_SEGREGACAO'
        , 'PR_FLG_CTRL_RESIDUAL'
        , 'PR_FLG_INSTALADO'
        , 'PR_QTD_RESIDUAL_MAX_ENV_PED'
        , 'PR_FLG_CTRL_VOLUME_ARMAZ'
        , 'PR_PER_COMISS_EC'
        , 'PR_FLG_CONF_QUALITATIVA'
        , 'PR_PESO_DRENADO'
        , 'ID_ECOMMERCE'
        , 'PR_DESC_VARIACAO'
        , 'GRPR_COD_COMPRA'
        , 'VAPR_COD'
        , 'VAPI_NUM_SEQ'
        , 'PR_MARG_MIN_CALC_PRC_AUTO'
        , 'PR_FLG_CAD_CONF'
        , 'PR_QTD_AGRUP_ARMAZ'
        , 'PR_FLG_MOV_TOTAL_WMS_PROD'
    ];
    protected $connection = 'oracle';
    // protected $primaryKey = ['PR_COD'];
    protected $table = 'PRDUTO';
    public $timestamps = false;

}
